# akonadictl
# Autogenerated from man page /usr/share/man/man1/akonadictl.1.gz
complete -c akonadictl -s h -l help -d 'show this help message'
complete -c akonadictl -l version -d 'show version information . SS "Multi-instance options:"'
complete -c akonadictl -l instance -d 'Namespace for starting multiple Akonadi instances in the same user session'

