# bup-gc
# Autogenerated from man page /usr/share/man/man1/bup-gc.1.gz
complete -c bup-gc -l threshold -d 'only rewrite a packfile if it\\[cq]s over N percent garbage; otherwise leave i…'
complete -c bup-gc -s v -l verbose -d 'increase verbosity (can be used more than once)'
complete -c bup-gc -s '#' -l compress -d 'set the compression level to # (a value from 0-9, where 9 is the highest and …'

