# bup-restore
# Autogenerated from man page /usr/share/man/man1/bup-restore.1.gz
complete -c bup-restore -s r -l remote -d 'restore the backup set from the given remote server'
complete -c bup-restore -s C -l outdir -d 'create and change to directory \\f[I]outdir\\f[R] before extracting the files'
complete -c bup-restore -l numeric-ids -d 'restore numeric IDs (user, group, etc. ) rather than names'
complete -c bup-restore -l exclude-rx -d 'exclude any path matching \\f[I]pattern\\f[R], which must be a Python regular e…'
complete -c bup-restore -l exclude-rx-from -d 'read \\[en]exclude-rx patterns from \\f[I]filename\\f[R], one pattern per-line (…'
complete -c bup-restore -l sparse -d 'write output data sparsely when reasonable'
complete -c bup-restore -l map-user -d 'for every path, restore the \\f[I]old\\f[R] (saved) user name as \\f[I]new\\f[R]'
complete -c bup-restore -l map-group -d 'for every path, restore the \\f[I]old\\f[R] (saved) group name as \\f[I]new\\f[R]'
complete -c bup-restore -l map-uid -d 'for every path, restore the \\f[I]old\\f[R] (saved) uid as \\f[I]new\\f[R], unles…'
complete -c bup-restore -l map-gid -d 'for every path, restore the \\f[I]old\\f[R] (saved) gid as \\f[I]new\\f[R], unles…'
complete -c bup-restore -s v -l verbose -d 'increase log output'
complete -c bup-restore -l name -s n
complete -c bup-restore -s q -l quiet -d 'suppress output, including the progress meter'
complete -c bup-restore -o rw-r--r-- -d 'Restore etc to test (no trailing slash): $ bup restore -C test /mybackup/late…'
complete -c bup-restore -o rw-r----- -d '# bup restore -C dest --map-user foo=bar --map-group baz=bax /x/latest/y Rest…'

