# bup-random
# Autogenerated from man page /usr/share/man/man1/bup-random.1.gz
complete -c bup-random -s S -l seed -d 'use the given value to seed the pseudorandom number generator'
complete -c bup-random -s f -l force -d 'generate output even if stdout is a tty'
complete -c bup-random -s v -l verbose -d 'print a progress message showing the number of bytes that has been output so …'

