# bup-midx
# Autogenerated from man page /usr/share/man/man1/bup-midx.1.gz
complete -c bup-midx -s o -l output -d 'use the given output filename for the \\f[V]. midx\\f[R] file'
complete -c bup-midx -s a -l auto -d 'automatically generate new \\f[V]. midx\\f[R] files for any \\f[V]'
complete -c bup-midx -s f -l force -d 'force generation of a single new \\f[V]'
complete -c bup-midx -l dir -d 'specify the directory containing the \\f[V]. idx\\f[R]/\\f[V]'
complete -c bup-midx -l max-files -d 'maximum number of \\f[V]. idx\\f[R] files to open at a time'
complete -c bup-midx -l check -d 'validate a . midx file by ensuring that all objects in its contained '

