# bup-cat-file
# Autogenerated from man page /usr/share/man/man1/bup-cat-file.1.gz
complete -c bup-cat-file -l meta -d 'retrieve the metadata entry associated with \\f[I]path\\f[R]'
complete -c bup-cat-file -l bupm -d 'entry in the output'

