# bup-import-rdiff-backup
# Autogenerated from man page /usr/share/man/man1/bup-import-rdiff-backup.1.gz
complete -c bup-import-rdiff-backup -s n -l dry-run -d 'don[cq]t do anything just print out what would be done EXAMPLES $ bup import-…'

