# bup-import-duplicity
# Autogenerated from man page /usr/share/man/man1/bup-import-duplicity.1.gz
complete -c bup-import-duplicity -l archive-dir -d '[ti]/. cache/duplicity.  OPTIONS'
complete -c bup-import-duplicity -s n -l dry-run -d 'don[cq]t do anything; just print out what would be done EXAMPLES $ bup import…'

