# bup-fsck
# Autogenerated from man page /usr/share/man/man1/bup-fsck.1.gz
complete -c bup-fsck -s r -l repair -d 'attempt to repair any damaged packs using existing recovery blocks'
complete -c bup-fsck -s g -l generate -d 'generate recovery blocks for any packs that don\\[cq]t already have them'
complete -c bup-fsck -s v -l verbose -d 'increase verbosity (can be used more than once)'
complete -c bup-fsck -l quick -d 'don\\[cq]t run a full \\f[V]git verify-pack\\f[R] on each pack file; instead jus…'
complete -c bup-fsck -s j -l jobs -d 'maximum number of pack verifications to run at a time'
complete -c bup-fsck -l par2-ok -d 'immediately return 0 if \\f[V]par2\\f[R](1) is installed and working, or 1 othe…'
complete -c bup-fsck -l disable-par2 -d 'pretend that par2(1) is not installed, and ignore all recovery blocks'

