# bup-damage
# Autogenerated from man page /usr/share/man/man1/bup-damage.1.gz
complete -c bup-damage -s n -l num -d 'the number of separate blocks to damage in each file (default 10)'
complete -c bup-damage -s s -l size -d 'the maximum size, in bytes, of each damaged block (default 1 unless \\f[V]--pe…'
complete -c bup-damage -l percent -d 'the maximum size, in percent of the original file, of each damaged block'
complete -c bup-damage -s S -l seed -d 'seed the random number generator with the given value'
complete -c bup-damage -l equal -d 'instead of choosing random offsets for each damaged block, space the blocks e…'

