# bup-get
# Autogenerated from man page /usr/share/man/man1/bup-get.1.gz
complete -c bup-get -s s -l source -d 'use \\f[I]path\\f[R] as the source repository, instead of the default'
complete -c bup-get -s r -l remote -d 'store the indicated items on the given remote server'
complete -c bup-get -s c -l print-commits -d 'for each updated branch, print the new git commit id'
complete -c bup-get -s t -l print-trees -d 'for each updated branch, print the new git tree id of the filesystem root'
complete -c bup-get -l print-tags -d 'for each updated tag, print the new git id'
complete -c bup-get -s v -l verbose -d 'increase verbosity (can be used more than once)'
complete -c bup-get -l bwlimit -d 'don\\[cq]t transmit more than \\f[I]bytes/sec\\f[R] bytes per second to the serv…'
complete -c bup-get -l append -l pick -l pick
complete -c bup-get -l force-pick -l force-pick -l new-tag
complete -c bup-get -l replace -l replace
complete -c bup-get -l unnamed -d 'See the EXAMPLES below for a quick introduction'
complete -c bup-get -l ff -l ff -d 'fast-forward dest to match ref'
complete -c bup-get -o vv -o vvv -d filename
complete -c bup-get -s '#' -l compress -d 'set the compression level to # (a value from 0-9, where 9 is the highest and …'

