# bup-import-rsnapshot
# Autogenerated from man page /usr/share/man/man1/bup-import-rsnapshot.1.gz
complete -c bup-import-rsnapshot -s n -l dry-run -d 'don[cq]t do anything just print out what would be done EXAMPLES $ bup import-…'

