# bup-prune-older
# Autogenerated from man page /usr/share/man/man1/bup-prune-older.1.gz
complete -c bup-prune-older -l keep-all-for -d 'when no smaller time scale \\f[V]--keep\\f[R] option applies, retain all saves …'
complete -c bup-prune-older -l keep-dailies-for -d 'when no smaller time scale \\f[V]--keep\\f[R] option applies, retain the newest…'
complete -c bup-prune-older -l keep-monthlies-for -d 'when no smaller time scale \\f[V]--keep\\f[R] option applies, retain the newest…'
complete -c bup-prune-older -l keep-yearlies-for -d 'when no smaller time scale \\f[V]--keep\\f[R] option applies, retain the newest…'
complete -c bup-prune-older -l wrt -d 'when computing a keep period, place the most recent end of the range at UTC_S…'
complete -c bup-prune-older -l pretend -d 'don\\[cq]t do anything, just list the actions that would be taken to standard …'
complete -c bup-prune-older -l gc -d 'garbage collect the repository after removing the relevant saves'
complete -c bup-prune-older -l gc-threshold -d 'only rewrite a packfile if it\\[cq]s over N percent garbage; otherwise leave i…'
complete -c bup-prune-older -o '\\f' -l compress -d 'set the compression level when rewriting archive data to # (a value from 0-9,…'
complete -c bup-prune-older -l no-gc
complete -c bup-prune-older -s '#' -d 'set the compression level when rewriting archive data to # (a value from 0-9,…'
complete -c bup-prune-older -s v -l verbose -d 'increase verbosity (can be specified more than once).  NOTES'

