# bup-memtest
# Autogenerated from man page /usr/share/man/man1/bup-memtest.1.gz
complete -c bup-memtest -s n -l number -d 'set the number of objects to search for during each cycle (ie'
complete -c bup-memtest -s c -l cycles -d 'set the number of cycles (ie.  the number of lines of output after the first)'
complete -c bup-memtest -l ignore-midx -d 'ignore any \\f[V]. midx\\f[R] files created by \\f[V]bup midx\\f[R]'
complete -c bup-memtest -l existing -d 'search for existing objects instead of searching for random nonexistent ones'

