# bup-daemon
# Autogenerated from man page /usr/share/man/man1/bup-daemon.1.gz
complete -c bup-daemon -s l -l listen -d 'the address or hostname to listen on'
complete -c bup-daemon -s p -l port -d 'the port to listen on BUP'

