# bup-margin
# Autogenerated from man page /usr/share/man/man1/bup-margin.1.gz
complete -c bup-margin -l predict -d 'Guess the offset into each index file where a particular object will appear, …'
complete -c bup-margin -l ignore-midx -d 'don[cq]t use . midx files, use only . idx files'

