# bup-tag
# Autogenerated from man page /usr/share/man/man1/bup-tag.1.gz
complete -c bup-tag -s d -l delete -d 'delete a tag'
complete -c bup-tag -s f -l force -d 'Overwrite the named tag even if it already exists'

