# bup-rm
# Autogenerated from man page /usr/share/man/man1/bup-rm.1.gz
complete -c bup-rm -s v -l verbose -d 'increase verbosity (can be used more than once)'
complete -c bup-rm -s '#' -l compress -d 'set the compression level to # (a value from 0-9, where 9 is the highest and …'

