# bup-ls
# Autogenerated from man page /usr/share/man/man1/bup-ls.1.gz
complete -c bup-ls -s r -l remote -d 'list information for the repository at \\f[I]path\\f[R] on the indicated \\f[I]h…'
complete -c bup-ls -s s -l hash -d 'show hash for each file/directory'
complete -c bup-ls -s a -l all -d 'show hidden files'
complete -c bup-ls -s A -l almost-all -d 'show hidden files, except \\[lq]. \\[rq] and \\[lq]. \\[rq]'
complete -c bup-ls -s d -l directory -d 'show information about directories themselves, rather than their contents, an…'
complete -c bup-ls -s l -d 'provide a detailed, long listing for each item'
complete -c bup-ls -s F -l classify -d 'append type indicator: dir/, symlink\\[at], fifo|, socket=, and executable*'
complete -c bup-ls -l file-type -d 'append type indicator: dir/, symlink\\[at], fifo|, socket='
complete -c bup-ls -l human-readable -d 'print human readable file sizes (i. e. 3. 9K, 4. 7M)'
complete -c bup-ls -s n -d 'of the backup, and subsequent levels correspond to files in the backup'
complete -c bup-ls -l numeric-ids -d 'display numeric IDs (user, group, etc. ) rather than names'

