# bup-fuse
# Autogenerated from man page /usr/share/man/man1/bup-fuse.1.gz
complete -c bup-fuse -s d -l debug -d 'run in the foreground and print FUSE debug information for each request'
complete -c bup-fuse -s f -l foreground -d 'run in the foreground and exit only when the filesystem is unmounted'
complete -c bup-fuse -s o -l allow-other -d 'permit other users to access the filesystem'
complete -c bup-fuse -l meta -d 'report some of the original metadata (when available) for the mounted paths (…'
complete -c bup-fuse -s v -l verbose -d 'increase verbosity (can be used more than once)'

