# bup-web
# Autogenerated from man page /usr/share/man/man1/bup-web.1.gz
complete -c bup-web -l human-readable -d 'display human readable file sizes (i. e. 3. 9K, 4. 7M)'
complete -c bup-web -l browser -d 'open the site in the default browser EXAMPLES $ bup web Serving HTTP on 127'

