# bup-drecurse
# Autogenerated from man page /usr/share/man/man1/bup-drecurse.1.gz
complete -c bup-drecurse -s x -l xdev -l one-file-system -d 'don\\[cq]t cross filesystem boundaries \\[en] though as with tar and rsync, the…'
complete -c bup-drecurse -s q -l quiet -d 'don\\[cq]t print filenames as they are encountered'
complete -c bup-drecurse -l exclude -d 'exclude \\f[I]path\\f[R] from the backup (may be repeated)'
complete -c bup-drecurse -l exclude-from -d 'read \\[en]exclude paths from \\f[I]filename\\f[R], one path per-line (may be re…'
complete -c bup-drecurse -l exclude-rx -d 'exclude any path matching \\f[I]pattern\\f[R]'
complete -c bup-drecurse -l exclude-rx-from -d 'read \\[en]exclude-rx patterns from \\f[I]filename\\f[R], one pattern per-line (…'
complete -c bup-drecurse -l profile -d 'print profiling information upon completion'

