# bup-bloom
# Autogenerated from man page /usr/share/man/man1/bup-bloom.1.gz
complete -c bup-bloom -l ruin -d 'destroy bloom filters by setting the whole bitmask to zeros'
complete -c bup-bloom -s f -l force -d 'don\\[cq]t update the existing bloom file; generate a new one from scratch'
complete -c bup-bloom -s d -l dir -d 'the directory, containing \\f[V]. idx\\f[R] files, to process'
complete -c bup-bloom -s o -l outfile -d 'the file to write the bloom filter to.  defaults to $dir/bup. bloom'
complete -c bup-bloom -s k -l hashes -d 'number of hash functions to use only 4 and 5 are valid'
complete -c bup-bloom -s c -l check -d 'checks the bloom file (counterintuitively outfile) against the specified '

