# bup
# Autogenerated from man page /usr/share/man/man1/bup.1.gz
complete -c bup -l version -d 'print bup[cq]s version number.  Equivalent to bup-version(1)'
complete -c bup -s d -l bup-dir -d 'use the given BUP_DIR parameter as the bup repository location, instead of re…'

