# cryfs-unmount
# Autogenerated from man page /usr/share/man/man1/cryfs-unmount.1.gz
complete -c cryfs-unmount -s h -l help -d ' Show a help message containing short descriptions for all options'
complete -c cryfs-unmount -l verson

