# cryptsetup-luksErase
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksErase.8.gz
complete -c cryptsetup-luksErase -l header
complete -c cryptsetup-luksErase -l disable-locks
complete -c cryptsetup-luksErase -l batch-mode -s q
complete -c cryptsetup-luksErase -l debug -l debug-json
complete -c cryptsetup-luksErase -l version -s V
complete -c cryptsetup-luksErase -l usage
complete -c cryptsetup-luksErase -l help -s '?'

