# cryptsetup-bitlkOpen
# Autogenerated from man page /usr/share/man/man8/cryptsetup-bitlkOpen.8.gz
complete -c cryptsetup-bitlkOpen -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-bitlkOpen -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-bitlkOpen -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-bitlkOpen -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-bitlkOpen -l test-passphrase -l header -l key-slot
complete -c cryptsetup-bitlkOpen -l volume-key-file -l token-only
complete -c cryptsetup-bitlkOpen -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-bitlkOpen -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-bitlkOpen -l persistent -d loopAES
complete -c cryptsetup-bitlkOpen -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-bitlkOpen -l tcrypt-backup
complete -c cryptsetup-bitlkOpen -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-bitlkOpen -l veracrypt-query-pim
complete -c cryptsetup-bitlkOpen -l cipher
complete -c cryptsetup-bitlkOpen -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-bitlkOpen -s h
complete -c cryptsetup-bitlkOpen -s c
complete -c cryptsetup-bitlkOpen -s y
complete -c cryptsetup-bitlkOpen -s d
complete -c cryptsetup-bitlkOpen -s l
complete -c cryptsetup-bitlkOpen -l master-key-file
complete -c cryptsetup-bitlkOpen -s S
complete -c cryptsetup-bitlkOpen -s s
complete -c cryptsetup-bitlkOpen -s b
complete -c cryptsetup-bitlkOpen -s o
complete -c cryptsetup-bitlkOpen -s p
complete -c cryptsetup-bitlkOpen -s r
complete -c cryptsetup-bitlkOpen -s t
complete -c cryptsetup-bitlkOpen -s T
complete -c cryptsetup-bitlkOpen -l perf-same_cpu_crypt
complete -c cryptsetup-bitlkOpen -l perf-submit_from_crypt_cpus
complete -c cryptsetup-bitlkOpen -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-bitlkOpen -l sector-size
complete -c cryptsetup-bitlkOpen -l integrity-no-journal -d persistently
complete -c cryptsetup-bitlkOpen -l tcrypt-system
complete -c cryptsetup-bitlkOpen -l batch-mode -s q
complete -c cryptsetup-bitlkOpen -l debug -l debug-json
complete -c cryptsetup-bitlkOpen -l version -s V
complete -c cryptsetup-bitlkOpen -l usage
complete -c cryptsetup-bitlkOpen -l help -s '?'

