# cryptsetup-luksOpen
# Autogenerated from man page /usr/share/man/man8/cryptsetup-luksOpen.8.gz
complete -c cryptsetup-luksOpen -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-luksOpen -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-luksOpen -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-luksOpen -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-luksOpen -l test-passphrase -l header -l key-slot
complete -c cryptsetup-luksOpen -l volume-key-file -l token-only
complete -c cryptsetup-luksOpen -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-luksOpen -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-luksOpen -l persistent -d loopAES
complete -c cryptsetup-luksOpen -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-luksOpen -l tcrypt-backup
complete -c cryptsetup-luksOpen -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-luksOpen -l veracrypt-query-pim
complete -c cryptsetup-luksOpen -l cipher
complete -c cryptsetup-luksOpen -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-luksOpen -s h
complete -c cryptsetup-luksOpen -s c
complete -c cryptsetup-luksOpen -s y
complete -c cryptsetup-luksOpen -s d
complete -c cryptsetup-luksOpen -s l
complete -c cryptsetup-luksOpen -l master-key-file
complete -c cryptsetup-luksOpen -s S
complete -c cryptsetup-luksOpen -s s
complete -c cryptsetup-luksOpen -s b
complete -c cryptsetup-luksOpen -s o
complete -c cryptsetup-luksOpen -s p
complete -c cryptsetup-luksOpen -s r
complete -c cryptsetup-luksOpen -s t
complete -c cryptsetup-luksOpen -s T
complete -c cryptsetup-luksOpen -l perf-same_cpu_crypt
complete -c cryptsetup-luksOpen -l perf-submit_from_crypt_cpus
complete -c cryptsetup-luksOpen -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-luksOpen -l sector-size
complete -c cryptsetup-luksOpen -l integrity-no-journal -d persistently
complete -c cryptsetup-luksOpen -l tcrypt-system
complete -c cryptsetup-luksOpen -l batch-mode -s q
complete -c cryptsetup-luksOpen -l debug -l debug-json
complete -c cryptsetup-luksOpen -l version -s V
complete -c cryptsetup-luksOpen -l usage
complete -c cryptsetup-luksOpen -l help -s '?'

