# cryptsetup-fvault2Open
# Autogenerated from man page /usr/share/man/man8/cryptsetup-fvault2Open.8.gz
complete -c cryptsetup-fvault2Open -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-fvault2Open -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-fvault2Open -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-fvault2Open -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-fvault2Open -l test-passphrase -l header -l key-slot
complete -c cryptsetup-fvault2Open -l volume-key-file -l token-only
complete -c cryptsetup-fvault2Open -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-fvault2Open -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-fvault2Open -l persistent -d loopAES
complete -c cryptsetup-fvault2Open -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-fvault2Open -l tcrypt-backup
complete -c cryptsetup-fvault2Open -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-fvault2Open -l veracrypt-query-pim
complete -c cryptsetup-fvault2Open -l cipher
complete -c cryptsetup-fvault2Open -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-fvault2Open -s h
complete -c cryptsetup-fvault2Open -s c
complete -c cryptsetup-fvault2Open -s y
complete -c cryptsetup-fvault2Open -s d
complete -c cryptsetup-fvault2Open -s l
complete -c cryptsetup-fvault2Open -l master-key-file
complete -c cryptsetup-fvault2Open -s S
complete -c cryptsetup-fvault2Open -s s
complete -c cryptsetup-fvault2Open -s b
complete -c cryptsetup-fvault2Open -s o
complete -c cryptsetup-fvault2Open -s p
complete -c cryptsetup-fvault2Open -s r
complete -c cryptsetup-fvault2Open -s t
complete -c cryptsetup-fvault2Open -s T
complete -c cryptsetup-fvault2Open -l perf-same_cpu_crypt
complete -c cryptsetup-fvault2Open -l perf-submit_from_crypt_cpus
complete -c cryptsetup-fvault2Open -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-fvault2Open -l sector-size
complete -c cryptsetup-fvault2Open -l integrity-no-journal -d persistently
complete -c cryptsetup-fvault2Open -l tcrypt-system
complete -c cryptsetup-fvault2Open -l batch-mode -s q
complete -c cryptsetup-fvault2Open -l debug -l debug-json
complete -c cryptsetup-fvault2Open -l version -s V
complete -c cryptsetup-fvault2Open -l usage
complete -c cryptsetup-fvault2Open -l help -s '?'

