# cryptsetup-plainOpen
# Autogenerated from man page /usr/share/man/man8/cryptsetup-plainOpen.8.gz
complete -c cryptsetup-plainOpen -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-plainOpen -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-plainOpen -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-plainOpen -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-plainOpen -l test-passphrase -l header -l key-slot
complete -c cryptsetup-plainOpen -l volume-key-file -l token-only
complete -c cryptsetup-plainOpen -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-plainOpen -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-plainOpen -l persistent -d loopAES
complete -c cryptsetup-plainOpen -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-plainOpen -l tcrypt-backup
complete -c cryptsetup-plainOpen -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-plainOpen -l veracrypt-query-pim
complete -c cryptsetup-plainOpen -l cipher
complete -c cryptsetup-plainOpen -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-plainOpen -s h
complete -c cryptsetup-plainOpen -s c
complete -c cryptsetup-plainOpen -s y
complete -c cryptsetup-plainOpen -s d
complete -c cryptsetup-plainOpen -s l
complete -c cryptsetup-plainOpen -l master-key-file
complete -c cryptsetup-plainOpen -s S
complete -c cryptsetup-plainOpen -s s
complete -c cryptsetup-plainOpen -s b
complete -c cryptsetup-plainOpen -s o
complete -c cryptsetup-plainOpen -s p
complete -c cryptsetup-plainOpen -s r
complete -c cryptsetup-plainOpen -s t
complete -c cryptsetup-plainOpen -s T
complete -c cryptsetup-plainOpen -l perf-same_cpu_crypt
complete -c cryptsetup-plainOpen -l perf-submit_from_crypt_cpus
complete -c cryptsetup-plainOpen -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-plainOpen -l sector-size
complete -c cryptsetup-plainOpen -l integrity-no-journal -d persistently
complete -c cryptsetup-plainOpen -l tcrypt-system
complete -c cryptsetup-plainOpen -l batch-mode -s q
complete -c cryptsetup-plainOpen -l debug -l debug-json
complete -c cryptsetup-plainOpen -l version -s V
complete -c cryptsetup-plainOpen -l usage
complete -c cryptsetup-plainOpen -l help -s '?'

