# cryptsetup-loopaesOpen
# Autogenerated from man page /usr/share/man/man8/cryptsetup-loopaesOpen.8.gz
complete -c cryptsetup-loopaesOpen -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-loopaesOpen -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-loopaesOpen -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-loopaesOpen -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-loopaesOpen -l test-passphrase -l header -l key-slot
complete -c cryptsetup-loopaesOpen -l volume-key-file -l token-only
complete -c cryptsetup-loopaesOpen -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-loopaesOpen -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-loopaesOpen -l persistent -d loopAES
complete -c cryptsetup-loopaesOpen -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-loopaesOpen -l tcrypt-backup
complete -c cryptsetup-loopaesOpen -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-loopaesOpen -l veracrypt-query-pim
complete -c cryptsetup-loopaesOpen -l cipher
complete -c cryptsetup-loopaesOpen -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-loopaesOpen -s h
complete -c cryptsetup-loopaesOpen -s c
complete -c cryptsetup-loopaesOpen -s y
complete -c cryptsetup-loopaesOpen -s d
complete -c cryptsetup-loopaesOpen -s l
complete -c cryptsetup-loopaesOpen -l master-key-file
complete -c cryptsetup-loopaesOpen -s S
complete -c cryptsetup-loopaesOpen -s s
complete -c cryptsetup-loopaesOpen -s b
complete -c cryptsetup-loopaesOpen -s o
complete -c cryptsetup-loopaesOpen -s p
complete -c cryptsetup-loopaesOpen -s r
complete -c cryptsetup-loopaesOpen -s t
complete -c cryptsetup-loopaesOpen -s T
complete -c cryptsetup-loopaesOpen -l perf-same_cpu_crypt
complete -c cryptsetup-loopaesOpen -l perf-submit_from_crypt_cpus
complete -c cryptsetup-loopaesOpen -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-loopaesOpen -l sector-size
complete -c cryptsetup-loopaesOpen -l integrity-no-journal -d persistently
complete -c cryptsetup-loopaesOpen -l tcrypt-system
complete -c cryptsetup-loopaesOpen -l batch-mode -s q
complete -c cryptsetup-loopaesOpen -l debug -l debug-json
complete -c cryptsetup-loopaesOpen -l version -s V
complete -c cryptsetup-loopaesOpen -l usage
complete -c cryptsetup-loopaesOpen -l help -s '?'

