# cryptsetup-create
# Autogenerated from man page /usr/share/man/man8/cryptsetup-create.8.gz
complete -c cryptsetup-create -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-create -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-create -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-create -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-create -l test-passphrase -l header -l key-slot
complete -c cryptsetup-create -l volume-key-file -l token-only
complete -c cryptsetup-create -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-create -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-create -l persistent -d loopAES
complete -c cryptsetup-create -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-create -l tcrypt-backup
complete -c cryptsetup-create -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-create -l veracrypt-query-pim
complete -c cryptsetup-create -l cipher
complete -c cryptsetup-create -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-create -s h
complete -c cryptsetup-create -s c
complete -c cryptsetup-create -s y
complete -c cryptsetup-create -s d
complete -c cryptsetup-create -s l
complete -c cryptsetup-create -l master-key-file
complete -c cryptsetup-create -s S
complete -c cryptsetup-create -s s
complete -c cryptsetup-create -s b
complete -c cryptsetup-create -s o
complete -c cryptsetup-create -s p
complete -c cryptsetup-create -s r
complete -c cryptsetup-create -s t
complete -c cryptsetup-create -s T
complete -c cryptsetup-create -l perf-same_cpu_crypt
complete -c cryptsetup-create -l perf-submit_from_crypt_cpus
complete -c cryptsetup-create -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-create -l sector-size
complete -c cryptsetup-create -l integrity-no-journal -d persistently
complete -c cryptsetup-create -l tcrypt-system
complete -c cryptsetup-create -l batch-mode -s q
complete -c cryptsetup-create -l debug -l debug-json
complete -c cryptsetup-create -l version -s V
complete -c cryptsetup-create -l usage
complete -c cryptsetup-create -l help -s '?'

