# cryptsetup-tcryptOpen
# Autogenerated from man page /usr/share/man/man8/cryptsetup-tcryptOpen.8.gz
complete -c cryptsetup-tcryptOpen -l key-file -l keyfile-size -l keyfile-offset -l key-size -l offset
complete -c cryptsetup-tcryptOpen -l skip -l device-size -l size -l readonly -l shared -l allow-discards
complete -c cryptsetup-tcryptOpen -l refresh -l timeout -l verify-passphrase -l iv-large-sectors
complete -c cryptsetup-tcryptOpen -l token-type -l token-id -d 'matching PIN protected token'
complete -c cryptsetup-tcryptOpen -l test-passphrase -l header -l key-slot
complete -c cryptsetup-tcryptOpen -l volume-key-file -l token-only
complete -c cryptsetup-tcryptOpen -l disable-external-tokens -l disable-keyring -l disable-locks -l type
complete -c cryptsetup-tcryptOpen -l serialize-memory-hard-pbkdf -l unbound -l tries
complete -c cryptsetup-tcryptOpen -l persistent -d loopAES
complete -c cryptsetup-tcryptOpen -l hash -d 'TrueCrypt and VeraCrypt'
complete -c cryptsetup-tcryptOpen -l tcrypt-backup
complete -c cryptsetup-tcryptOpen -l veracrypt -l disable-veracrypt -l veracrypt-pim
complete -c cryptsetup-tcryptOpen -l veracrypt-query-pim
complete -c cryptsetup-tcryptOpen -l cipher
complete -c cryptsetup-tcryptOpen -l tcrypt-hidden -d 'hidden volume (hidden volume appears as unused space for outer volume so this…'
complete -c cryptsetup-tcryptOpen -s h
complete -c cryptsetup-tcryptOpen -s c
complete -c cryptsetup-tcryptOpen -s y
complete -c cryptsetup-tcryptOpen -s d
complete -c cryptsetup-tcryptOpen -s l
complete -c cryptsetup-tcryptOpen -l master-key-file
complete -c cryptsetup-tcryptOpen -s S
complete -c cryptsetup-tcryptOpen -s s
complete -c cryptsetup-tcryptOpen -s b
complete -c cryptsetup-tcryptOpen -s o
complete -c cryptsetup-tcryptOpen -s p
complete -c cryptsetup-tcryptOpen -s r
complete -c cryptsetup-tcryptOpen -s t
complete -c cryptsetup-tcryptOpen -s T
complete -c cryptsetup-tcryptOpen -l perf-same_cpu_crypt
complete -c cryptsetup-tcryptOpen -l perf-submit_from_crypt_cpus
complete -c cryptsetup-tcryptOpen -l perf-no_read_workqueue -l perf-no_write_workqueue
complete -c cryptsetup-tcryptOpen -l sector-size
complete -c cryptsetup-tcryptOpen -l integrity-no-journal -d persistently
complete -c cryptsetup-tcryptOpen -l tcrypt-system
complete -c cryptsetup-tcryptOpen -l batch-mode -s q
complete -c cryptsetup-tcryptOpen -l debug -l debug-json
complete -c cryptsetup-tcryptOpen -l version -s V
complete -c cryptsetup-tcryptOpen -l usage
complete -c cryptsetup-tcryptOpen -l help -s '?'

