# delgroup
# Autogenerated from man page /usr/share/man/man8/delgroup.8.gz
complete -c delgroup -l backup -d 'Backup all files contained in the userhome and the mailspool file to a file n…'
complete -c delgroup -l backup-suffix -d 'Select compression algorithm for a home directory backup'
complete -c delgroup -l backup-to -d 'Place the backup files not in the current directory but in dir'
complete -c delgroup -l conf -d 'Use file instead of the default files /etc/deluser. conf and /etc/adduser'
complete -c delgroup -l debug -d 'Activate debugging code'
complete -c delgroup -l group -d 'Remove a group'
complete -c delgroup -l help -d 'Display brief instructions'
complete -c delgroup -l only-if-empty -d 'Only remove if no members are left.  Valid Modes: deluser --group, delgroup,'
complete -c delgroup -l quiet -d 'Suppress informational messages, only show warnings and errors'
complete -c delgroup -l remove-all-files -d 'Remove all files from the system owned by this user'
complete -c delgroup -l remove-home -d 'Remove the home directory of the user and its mailspool'
complete -c delgroup -l system -d 'Only delete if user/group is a system user/group'
complete -c delgroup -l verbose -d 'Be more verbose'
complete -c delgroup -l version -d 'Display version and copyright information.  RETURN VALUE'

