# exo-desktop-item-edit
# Autogenerated from man page /usr/share/man/man1/exo-desktop-item-edit.1.gz
complete -c exo-desktop-item-edit -s h -l help -d 'Show help options'
complete -c exo-desktop-item-edit -l help-all -d 'Show all help options'
complete -c exo-desktop-item-edit -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c exo-desktop-item-edit -s c -l create-new -d 'Create a new desktop file in the given directory'
complete -c exo-desktop-item-edit -s t -l type -d 'Type of desktop file to create (Application or Link)'
complete -c exo-desktop-item-edit -l name -d 'Preset name when creating a desktop file'
complete -c exo-desktop-item-edit -l comment -d 'Preset comment when creating a desktop file'
complete -c exo-desktop-item-edit -l command -d 'Preset command when creating a launcher'
complete -c exo-desktop-item-edit -l url -d 'Preset URL when creating a link'
complete -c exo-desktop-item-edit -l icon -d 'Preset icon when creating a desktop file'
complete -c exo-desktop-item-edit -s V -l version -d 'Print version information and exit'
complete -c exo-desktop-item-edit -l display -d 'X display to use AUTHOR Written by Benedikt Meurer <benny@xfce. org>'

