# eyuvtoppm
# Autogenerated from man page /usr/share/man/man1/eyuvtoppm.1.gz
complete -c eyuvtoppm -l width -d 'Width of the image, in pixels.   Must be an even number'
complete -c eyuvtoppm -l height -d 'Height of the image, in pixels.   Must be an even number'

