# hdifftopam
# Autogenerated from man page /usr/share/man/man1/hdifftopam.1.gz
complete -c hdifftopam -o pnm -d 'This option tells hdifftopam to create a PNM image (i. e.  PGM or      PPM)'
complete -c hdifftopam -o verbose -d 'Print output image width, height, depth and maxval to standard error'

