# jbigtopnm
# Autogenerated from man page /usr/share/man/man1/jbigtopnm.1.gz
complete -c jbigtopnm -o xmax -d 'Decode only up to the largest resolution layer which is still not more than n…'
complete -c jbigtopnm -o ymax -d 'Decode only up to the largest resolution layer which is still not more than n…'
complete -c jbigtopnm -o binary -d 'Use binary values instead of Gray code words in order to decode pixel values …'
complete -c jbigtopnm -o diagnose -d 'Diagnose a BIE'
complete -c jbigtopnm -o plane -d 'If the input contains multiple bitplanes, then extract only the specified sin…'
complete -c jbigtopnm -s x -s y -d 'satisfies both limits'

