# kup-daemon
# Autogenerated from man page /usr/share/man/man1/kup-daemon.1.gz
complete -c kup-daemon -s v -l version -d 'Show version information'
complete -c kup-daemon -s h -l help -d 'Show summary of options and basic help'
complete -c kup-daemon -l author -d 'Show author information'
complete -c kup-daemon -l license -d 'Show license information'
complete -c kup-daemon -l desktopfile -d 'The base file name of the desktop entry for this application'

