# kup-filedigger
# Autogenerated from man page /usr/share/man/man1/kup-filedigger.1.gz
complete -c kup-filedigger -s v -l version -d 'Show version information'
complete -c kup-filedigger -s h -l help -d 'Show summary of options and basic help'
complete -c kup-filedigger -s b -l branch -d 'Name of the branch to be opened'
complete -c kup-filedigger -l author -d 'Show author information'
complete -c kup-filedigger -l license -d 'Show license information'
complete -c kup-filedigger -l desktopfile -d 'The base file name of the desktop entry for this application.  ARGUMENTS'

