# mariadb-install-db
# Autogenerated from man page /usr/share/man/man1/mariadb-install-db.1.gz
complete -c mariadb-install-db -l user -d 'option to indicate the user name that mysqld will run as'
complete -c mariadb-install-db -l basedir -d or
complete -c mariadb-install-db -l datadir -d 'if mysql_install_db does not use the correct locations for the installation d…'
complete -c mariadb-install-db -l bootstrap -d and
complete -c mariadb-install-db -l skip-grant-tables -d 'options (see Section 2. 3. 2, “Typical configure Options”)'
complete -c mariadb-install-db -l disable-grant-options -d 'option,'
complete -c mariadb-install-db -l builddir
complete -c mariadb-install-db -l cross-bootstrap
complete -c mariadb-install-db -l ldata
complete -c mariadb-install-db -l defaults-extra-file
complete -c mariadb-install-db -l defaults-file
complete -c mariadb-install-db -l defaults-group-suffix
complete -c mariadb-install-db -l force
complete -c mariadb-install-db -l help
complete -c mariadb-install-db -l no-defaults
complete -c mariadb-install-db -l print-defaults
complete -c mariadb-install-db -l rpm
complete -c mariadb-install-db -l skip-name-resolve
complete -c mariadb-install-db -l srcdir
complete -c mariadb-install-db -l extra-file
complete -c mariadb-install-db -l verbose
complete -c mariadb-install-db -l windows

