# mariadb
# Autogenerated from man page /usr/share/man/man1/mariadb.1.gz
complete -c mariadb -l quick -d option
complete -c mariadb -l help
complete -c mariadb -s '?'
complete -c mariadb -s I
complete -c mariadb -l abort-source-on-error
complete -c mariadb -l auto-rehash
complete -c mariadb -l disable-auto-rehash -l no-auto-rehash -l skip-auto-rehash -d 'to disable rehashing'
complete -c mariadb -l auto-vertical-output
complete -c mariadb -l batch
complete -c mariadb -s B
complete -c mariadb -l raw -d 'option.  oc o 2. 3'
complete -c mariadb -l binary-mode
complete -c mariadb -l character-sets-dir
complete -c mariadb -l column-names
complete -c mariadb -l column-type-info
complete -c mariadb -s m
complete -c mariadb -l comments
complete -c mariadb -s c
complete -c mariadb -l compress
complete -c mariadb -s C
complete -c mariadb -l connect-timeout
complete -c mariadb -l database
complete -c mariadb -s D
complete -c mariadb -l debug
complete -c mariadb -s '#'
complete -c mariadb -l debug-check
complete -c mariadb -l debug-info
complete -c mariadb -s T
complete -c mariadb -l default-auth
complete -c mariadb -l default-character-set
complete -c mariadb -l defaults-extra-file
complete -c mariadb -l defaults-file
complete -c mariadb -l defaults-group-suffix
complete -c mariadb -l delimiter
complete -c mariadb -l disable-named-commands
complete -c mariadb -l enable-cleartext-plugin
complete -c mariadb -l execute
complete -c mariadb -s e
complete -c mariadb -l force
complete -c mariadb -s f
complete -c mariadb -l host
complete -c mariadb -s h
complete -c mariadb -l html
complete -c mariadb -s H
complete -c mariadb -l ignore-spaces
complete -c mariadb -s i
complete -c mariadb -l init-command
complete -c mariadb -l line-numbers
complete -c mariadb -l skip-line-numbers -d 'oc o 2. 3'
complete -c mariadb -l local-infile
complete -c mariadb -l max-allowed-packet
complete -c mariadb -l max-join-size
complete -c mariadb -l safe-updates -d 'oc o 2. 3'
complete -c mariadb -l named-commands
complete -c mariadb -s G
complete -c mariadb -l skip-named-commands -d 'to disable named commands.  See the section called “MYSQL COMMANDS”'
complete -c mariadb -l net-buffer-length
complete -c mariadb -s A
complete -c mariadb -l no-beep
complete -c mariadb -s b
complete -c mariadb -l no-defaults
complete -c mariadb -l one-database
complete -c mariadb -s o
complete -c mariadb -l pager
complete -c mariadb -l skip-pager -d 'the section called “MYSQL COMMANDS”, discusses output paging further.  oc o 2'
complete -c mariadb -l password
complete -c mariadb -s p
complete -c mariadb -l pipe
complete -c mariadb -s W
complete -c mariadb -l plugin-dir
complete -c mariadb -l port
complete -c mariadb -s P
complete -c mariadb -l print-defaults
complete -c mariadb -l progress-reports
complete -c mariadb -l prompt
complete -c mariadb -l protocol
complete -c mariadb -s q
complete -c mariadb -s r
complete -c mariadb -l silent -d 'option is given), special characters are escaped in the output so they can be…'
complete -c mariadb -l reconnect
complete -c mariadb -l skip-reconnect -l disable-reconnect -d 'oc o 2. 3'
complete -c mariadb -l i-am-a-dummy
complete -c mariadb -s U
complete -c mariadb -l secure-auth
complete -c mariadb -l select-limit
complete -c mariadb -l server-arg
complete -c mariadb -l show-warnings
complete -c mariadb -l sigint-ignore
complete -c mariadb -s s
complete -c mariadb -l skip-column-names
complete -c mariadb -s N
complete -c mariadb -s L
complete -c mariadb -l socket
complete -c mariadb -s S
complete -c mariadb -l ssl
complete -c mariadb -l skip-ssl -d 'oc o 2. 3'
complete -c mariadb -l ssl-ca
complete -c mariadb -l ssl-capath
complete -c mariadb -l ssl-cert
complete -c mariadb -l ssl-cipher
complete -c mariadb -l ssl-key
complete -c mariadb -l ssl-crl
complete -c mariadb -l ssl-crlpath
complete -c mariadb -l ssl-verify-server-cert
complete -c mariadb -l table
complete -c mariadb -s t
complete -c mariadb -l tee
complete -c mariadb -l unbuffered
complete -c mariadb -s n
complete -c mariadb -l user
complete -c mariadb -s u
complete -c mariadb -l verbose
complete -c mariadb -s v
complete -c mariadb -l version
complete -c mariadb -s V
complete -c mariadb -l vertical
complete -c mariadb -s E
complete -c mariadb -l wait
complete -c mariadb -s w
complete -c mariadb -l xml
complete -c mariadb -s X
complete -c mariadb -l var_name -d 'oc o 2. 3 connect_timeout'
complete -c mariadb -s F -d and

