# mariadb-upgrade
# Autogenerated from man page /usr/share/man/man1/mariadb-upgrade.1.gz
complete -c mariadb-upgrade -l all-databases -d 'option, it processes all tables in all databases, which might take a long tim…'
complete -c mariadb-upgrade -l check-upgrade -d 'option entails, see the description of the FOR UPGRADE option of the CHECK TA…'
complete -c mariadb-upgrade -l force -d option
complete -c mariadb-upgrade -l password -d 'option.  mysql_upgrade also supports the options for processing option files'
complete -c mariadb-upgrade -l help
complete -c mariadb-upgrade -s '?'
complete -c mariadb-upgrade -l basedir
complete -c mariadb-upgrade -l character-sets-dir
complete -c mariadb-upgrade -l check-if-upgrade-is-needed
complete -c mariadb-upgrade -l datadir
complete -c mariadb-upgrade -l debug
complete -c mariadb-upgrade -s '#'
complete -c mariadb-upgrade -l debug-check
complete -c mariadb-upgrade -l debug-info
complete -c mariadb-upgrade -s T
complete -c mariadb-upgrade -l default-character-set
complete -c mariadb-upgrade -l host
complete -c mariadb-upgrade -s p
complete -c mariadb-upgrade -l port
complete -c mariadb-upgrade -s P
complete -c mariadb-upgrade -l protocol
complete -c mariadb-upgrade -l silent
complete -c mariadb-upgrade -l socket
complete -c mariadb-upgrade -s S
complete -c mariadb-upgrade -l ssl
complete -c mariadb-upgrade -l skip-ssl -d 'oc o 2. 3'
complete -c mariadb-upgrade -l ssl-ca
complete -c mariadb-upgrade -l ssl-capath
complete -c mariadb-upgrade -l ssl-cert
complete -c mariadb-upgrade -l ssl-cipher
complete -c mariadb-upgrade -l ssl-key
complete -c mariadb-upgrade -l ssl-crl
complete -c mariadb-upgrade -l ssl-crlpath
complete -c mariadb-upgrade -l ssl-verify-server-cert
complete -c mariadb-upgrade -l tmpdir
complete -c mariadb-upgrade -s t
complete -c mariadb-upgrade -l upgrade-system-tables
complete -c mariadb-upgrade -s s
complete -c mariadb-upgrade -l user
complete -c mariadb-upgrade -s u
complete -c mariadb-upgrade -l verbose
complete -c mariadb-upgrade -l version
complete -c mariadb-upgrade -s V
complete -c mariadb-upgrade -l version-check
complete -c mariadb-upgrade -s k
complete -c mariadb-upgrade -l write-binlog

