# mariadb-check
# Autogenerated from man page /usr/share/man/man1/mariadb-check.1.gz
complete -c mariadb-check -l databases -d or
complete -c mariadb-check -l all-databases -d 'option to process all tables in one or more databases, an invocation of mysql…'
complete -c mariadb-check -l help
complete -c mariadb-check -s '?'
complete -c mariadb-check -s A
complete -c mariadb-check -l all-in-1
complete -c mariadb-check -s 1
complete -c mariadb-check -l analyze
complete -c mariadb-check -s a
complete -c mariadb-check -l auto-repair
complete -c mariadb-check -l character-sets-dir
complete -c mariadb-check -l check
complete -c mariadb-check -s c
complete -c mariadb-check -l check-only-changed
complete -c mariadb-check -s C
complete -c mariadb-check -l check-upgrade
complete -c mariadb-check -s g
complete -c mariadb-check -l fix-db-names -d and
complete -c mariadb-check -l fix-table-names -d 'options.  oc o 2. 3'
complete -c mariadb-check -l compress
complete -c mariadb-check -s B
complete -c mariadb-check -l debug
complete -c mariadb-check -s '#'
complete -c mariadb-check -l debug-check
complete -c mariadb-check -l debug-info
complete -c mariadb-check -l default-auth
complete -c mariadb-check -l default-character-set
complete -c mariadb-check -l defaults-extra-file
complete -c mariadb-check -l defaults-file
complete -c mariadb-check -l extended
complete -c mariadb-check -s e
complete -c mariadb-check -l fast
complete -c mariadb-check -s F
complete -c mariadb-check -l flush
complete -c mariadb-check -l force
complete -c mariadb-check -s f
complete -c mariadb-check -l host
complete -c mariadb-check -s h
complete -c mariadb-check -l medium-check
complete -c mariadb-check -s m
complete -c mariadb-check -l no-defaults
complete -c mariadb-check -l optimize
complete -c mariadb-check -s o
complete -c mariadb-check -l password
complete -c mariadb-check -s p
complete -c mariadb-check -l persistent
complete -c mariadb-check -s Z
complete -c mariadb-check -l pipe
complete -c mariadb-check -s W
complete -c mariadb-check -l plugin-dir
complete -c mariadb-check -l port
complete -c mariadb-check -s P
complete -c mariadb-check -l print-defaults
complete -c mariadb-check -l process-tables
complete -c mariadb-check -l process-views
complete -c mariadb-check -l protocol
complete -c mariadb-check -l quick
complete -c mariadb-check -s q
complete -c mariadb-check -l repair
complete -c mariadb-check -s r
complete -c mariadb-check -l silent
complete -c mariadb-check -s s
complete -c mariadb-check -l skip-database
complete -c mariadb-check -l socket
complete -c mariadb-check -s S
complete -c mariadb-check -l ssl
complete -c mariadb-check -l skip-ssl -d 'oc o 2. 3'
complete -c mariadb-check -l ssl-ca
complete -c mariadb-check -l ssl-capath
complete -c mariadb-check -l ssl-cert
complete -c mariadb-check -l ssl-cipher
complete -c mariadb-check -l ssl-key
complete -c mariadb-check -l ssl-crl
complete -c mariadb-check -l ssl-crlpath
complete -c mariadb-check -l ssl-verify-server-cert
complete -c mariadb-check -l tables
complete -c mariadb-check -l use-frm
complete -c mariadb-check -l user
complete -c mariadb-check -s u
complete -c mariadb-check -l verbose
complete -c mariadb-check -s v
complete -c mariadb-check -l version
complete -c mariadb-check -s V
complete -c mariadb-check -l write-binlog
complete -c mariadb-check -l skip-write-binlog -d 'to cause NO_WRITE_TO_BINLOG to be added to the statements so that they are no…'

