# mousepad
# Autogenerated from man page /usr/share/man/man1/mousepad.1.gz
complete -c mousepad -s h -l help -d 'Show help options'
complete -c mousepad -l help-all -d 'Show all help options'
complete -c mousepad -l help-gtk -d 'Show GTK+ Options'
complete -c mousepad -l class -d 'Program class as used by the window manager'
complete -c mousepad -l name -d 'Program name as used by the window manager'
complete -c mousepad -l screen -d 'X screen to use'
complete -c mousepad -l sync -d 'Make X calls synchronous'
complete -c mousepad -l gtk-module -d 'Load additional GTK+ modules'
complete -c mousepad -l g-fatal-warnings -d 'Make all warnings fatal Application Options:'
complete -c mousepad -l disable-server -d 'Do not register with the D-BUS session message bus'
complete -c mousepad -s q -l quit -d 'Quit a running Mousepad instance'
complete -c mousepad -s v -l version -d 'Print version information and exit'
complete -c mousepad -l display -d 'X display to use COPYRIGHT Copyright © 2007 The Xfce development team'

