# operon
# Autogenerated from man page /usr/share/man/man1/operon.1.gz
complete -c operon -s h -l help -d 'Display help and exit'
complete -c operon -l version -d 'Print the program version'
complete -c operon -s v -l verbose -d 'Verbose mode'
complete -c operon -l dry-run -d 'Print the results without changing any files'
complete -c operon -s e -l regexp -d 'Remove all tag values that match the given regular expression Example: operon…'
complete -c operon -s a -l all -d 'Remove all tags'
complete -c operon -l ignore-errors -d 'Skip tags which the target file does not support Example: operon copy song'
complete -c operon -s t -l terse -d 'Output is terse and suitable for script processing'
complete -c operon -s c -l columns -d 'Defines which columns should be printed and in which order'
complete -c operon -s p -l pattern -d 'Use a custom pattern Example: operon print -p "<album> - <artist>" a. ogg'
complete -c operon -l primary -d 'Only extract the primary images for each file'
complete -c operon -s d -l destination -d 'Save all images to the specified destination Example: operon image-extract as…'

