# pamaltsat
# Autogenerated from man page /usr/share/man/man1/pamaltsat.1.gz
complete -c pamaltsat -o method -d 'specifies the saturation method to use: '
complete -c pamaltsat -o strength -d 'This specifies a real nonnegative factor whereby to modify saturation'
complete -c pamaltsat -o linear -d 'This tells pamaltsat that the input is the intensity-linear variation of a Ne…'

