# pambrighten
# Autogenerated from man page /usr/share/man/man1/pambrighten.1.gz
complete -c pambrighten -o value -d 'This option specifies the amount, as a percentage, by which you want to incre…'
complete -c pambrighten -o saturation -d 'This option specifies the amount, as a percentage, by which you want to incre…'

