# pamcrater
# Autogenerated from man page /usr/share/man/man1/pamcrater.1.gz
complete -c pamcrater -o number -d 'This causes pamcrater to generate n craters'
complete -c pamcrater -o height -d 'This sets the height of the generated image to height pixels'
complete -c pamcrater -o width -d 'This sets the width of the generated image to width pixels'
complete -c pamcrater -o randomseed -d 'This is the seed for the random number generator that generates the pixels'
complete -c pamcrater -o verbose -d 'This causes pamcrater to issue additional messages about what it is doing'

