# pamditherbw
# Autogenerated from man page /usr/share/man/man1/pamditherbw.1.gz
complete -c pamditherbw -o value -d 'This option alters the thresholding value for Floyd-Steinberg, Atkinson, and …'
complete -c pamditherbw -o clump -d 'This option alters the number of pixels in a clump when the Hilbert curve met…'
complete -c pamditherbw -o randomseed -d 'The Floyd-Steiberg and Atkinson methods use random numbers to diffuse the err…'
complete -c pamditherbw -o atkinson -d AUTHOR

