# pamenlarge
# Autogenerated from man page /usr/share/man/man1/pamenlarge.1.gz
complete -c pamenlarge -o yscale -d 'These specify the scale factor'
complete -c pamenlarge -o scale
complete -c pamenlarge -o xscale

