# pamfix
# Autogenerated from man page /usr/share/man/man1/pamfix.1.gz
complete -c pamfix -o truncate -d 'Create a truncated output image from all the valid input rows that could be r…'
complete -c pamfix -o changemaxval -d 'Raise the maxval to cope with pixel values that exceed the maxval stated in t…'
complete -c pamfix -o clip -d 'Change all pixel values that exceed the maxval stated in the header of the in…'
complete -c pamfix -o verbose -d 'Report details of the transportation to standard error'

