# pamfile
# Autogenerated from man page /usr/share/man/man1/pamfile.1.gz
complete -c pamfile -o allimages -d 'This option causes pamfile to describe every image in each input file'
complete -c pamfile -o comments -d 'This option causes pamfile to include for each PAM image a report of the comm…'
complete -c pamfile -o count -d 'This option causes pamfile to display only a count of how many images are in …'
complete -c pamfile -o machine -d 'This makes the output more convenient for a machine to use, while   less conv…'
complete -c pamfile -o size -d 'This makes the output contain only the height and width of the image, in a fo…'

