# pamfind
# Autogenerated from man page /usr/share/man/man1/pamfind.1.gz
complete -c pamfind -o target -d 'This specifies the tuple value to find'
complete -c pamfind -o color -d 'This is the color to find, assuming the image is a color visual image'
complete -c pamfind -o machine -d 'This makes the output more convenient for a machine to use, while   less conv…'

