# pamgauss
# Autogenerated from man page /usr/share/man/man1/pamgauss.1.gz
complete -c pamgauss -o sigma -d 'This is the standard deviation of the Gaussian function'
complete -c pamgauss -o maximize -d 'Causes pamgauss to use the whole dynamic range available in the output PAM im…'
complete -c pamgauss -o maxval -d 'This is the maxval for the output image'
complete -c pamgauss -o tupletype -d 'This is the value of the "tuple_type" attribute of the created PAM image'
complete -c pamgauss -o oversample -d 'This sets the oversampling factor'

