# pamgetcolor
# Autogenerated from man page /usr/share/man/man1/pamgetcolor.1.gz
complete -c pamgetcolor -o format -d 'This specifies the format in which to output the colors'
complete -c pamgetcolor -o radius -d 'sets the radius of the regions'
complete -c pamgetcolor -o infile -d 'This specifies the Netpbm file to analyze'
complete -c pamgetcolor -o linear -d 'This tells pamgetcolor to work with the intensity-linear variation of Netpbm …'

