# pamhomography
# Autogenerated from man page /usr/share/man/man1/pamhomography.1.gz
complete -c pamhomography -o from -d 'sp This defines the source quadrilateral'
complete -c pamhomography -o to -d 'sp This defines the target quadrilateral'
complete -c pamhomography -o mapfile -d 'sp This names a text file that describes the mapping from the source to the t…'
complete -c pamhomography -o view -d 'sp This defines the target view'
complete -c pamhomography -o fill -d 'sp This is the color with which the program fills all pixels that lie outside…'
complete -c pamhomography -o '67.1281' -d '& 1. 0000 & 1. 0000 \\end{bmatrix} \\quad, \\]'

