# pamlevels
# Autogenerated from man page /usr/share/man/man1/pamlevels.1.gz
complete -c pamlevels -o to3 -d 'These options define the mappings of input colors to output colors that ancho…'
complete -c pamlevels -o linear -d 'This option tells pamlevels to work with the intensity-linear variation on PP…'
complete -c pamlevels -o fitbrightness -d 'This option selects a transformation which is not very useful - it is linear …'
complete -c pamlevels -o 't1...-t3'
complete -c pamlevels -o from1
complete -c pamlevels -o to1
complete -c pamlevels -o from2
complete -c pamlevels -o to2
complete -c pamlevels -o from3

