# pammixmulti
# Autogenerated from man page /usr/share/man/man1/pammixmulti.1.gz
complete -c pammixmulti -l blend -d 'sp This option specifies how the input images should be mixed to produce the …'
complete -c pammixmulti -l maskfile -d 'sp In conjunction with --blend=\\f(CWmask, this option names a grayscale mask …'
complete -c pammixmulti -l stdev -d 'sp When used with --blend=\\f(CWmask, this option controls how smoothly the va…'
complete -c pammixmulti -l randomseed -d 'This is the seed for the random number generator used with --blend=random '

