# pampaintspill
# Autogenerated from man page /usr/share/man/man1/pampaintspill.1.gz
complete -c pampaintspill -l bgcolor -d 'Explicitly specify the background color'
complete -c pampaintspill -l wrap -d 'Allow gradients to wrap around image borders'
complete -c pampaintspill -l all -d 'Recolor all pixels, not just background pixels'
complete -c pampaintspill -l downsample -d 'Ignore all but number non-background-colored pixels'
complete -c pampaintspill -l near -d 'Consider only the nearest number paint sources when computing       a pixel\'s…'
complete -c pampaintspill -l power -d 'Control how color intensity changes as a function of the       distance from …'
complete -c pampaintspill -o randomseed -d 'This is the seed for the random number generator that generates the   pixels'

