# pamrecolor
# Autogenerated from man page /usr/share/man/man1/pamrecolor.1.gz
complete -c pamrecolor -l colorspace -d 'Designate the color space to use for determining the contribution to luminanc…'
complete -c pamrecolor -l bmult -d 'Instead of selecting a color space by name, you can specify explicitly the co…'
complete -c pamrecolor -l targetcolor -d 'Designate color as the target color for the image'
complete -c pamrecolor -l colorfile -d 'Take per-pixel target colors from Netpbm file file instead of using a single …'
complete -c pamrecolor -o randomseed -d 'This is the seed for the random number generator that generates the pixels'
complete -c pamrecolor -l rmult
complete -c pamrecolor -l gmult

