# pamsistoaglyph
# Autogenerated from man page /usr/share/man/man1/pamsistoaglyph.1.gz
complete -c pamsistoaglyph -l invert -d 'Swap the left- and right-eye     images'
complete -c pamsistoaglyph -l sep -d 'Specify the distance in pixels between the left- and right-eye     images'
complete -c pamsistoaglyph -l minsep -d 'This option is similar to --sep but     constrains pamsistoaglyph only to    …'
complete -c pamsistoaglyph -l gray -d 'Limit the number of gray levels to use when searching for the     optimal eye…'

