# pamshadedrelief
# Autogenerated from man page /usr/share/man/man1/pamshadedrelief.1.gz
complete -c pamshadedrelief -s g -d 'The specified factor is used to gamma adjust the image in the same manner as …'
complete -c pamshadedrelief -o gamma

