# pamscale
# Autogenerated from man page /usr/share/man/man1/pamscale.1.gz
complete -c pamscale -o xysize -d 'These options determine the horizontal and vertical scale factors. sp   See  '
complete -c pamscale -o reportonly -d 'This causes pamscale not to scale the image, but instead to   report to Stand…'
complete -c pamscale -o nomix -d 'This option selects  . UR #sampling discrete sampling . UE  as the    '
complete -c pamscale -o filter -d 'This option selects  . UR #resampling resampling . UE  as the    '
complete -c pamscale -o window -d 'This option selects a window function to modify the filter function   specifi…'
complete -c pamscale -o verbose -d 'This option causes pamscale to issue messages to Standard Error about   the s…'
complete -c pamscale -o xscale -o yscale -o xyfit -o xyfill -o reduce -d 'and -pixels control the amount of scaling'
complete -c pamscale -o width -o height -d 'you want the resulting image to be'
complete -c pamscale -o xsize -o ysize
complete -c pamscale -o pixels -d 'pamscale scales the image down to that number of pixels'
complete -c pamscale -o windowoption -d 'to figure out just what the function is and what kind of scaling it does'
complete -c pamscale -o linear

