# pamtotga
# Autogenerated from man page /usr/share/man/man1/pamtotga.1.gz
complete -c pamtotga -o cmap -d 'Make output Targa file use a color map (palette) to make the output smaller'
complete -c pamtotga -o cmap16 -d 'Same as -cmap, except a color map entry for full color input is 5 bits each o…'
complete -c pamtotga -o mono -d 'Make output Targa file of type 8 bit monochrome'
complete -c pamtotga -o rgb -d 'Make output Targa file of type 24 bit unmapped color.   See -cmap'
complete -c pamtotga -o norle -d 'Do not use run-length encoding in the output Targa file'
complete -c pamtotga -o name -d 'This is the value for the image ID stated in the header of the TGA output file'
complete -c pamtotga -o verbose -d 'This causes pamtotga to issues messages about the conversion process'

