# pamtris
# Autogenerated from man page /usr/share/man/man1/pamtris.1.gz
complete -c pamtris -o width -d 'Sets the width of the internal frame buffer and, by extension, of the output …'
complete -c pamtris -o height -d 'This is the height of the internal frame buffer and, by extension, of the out…'
complete -c pamtris -o num_attribs -d 'This is the number of attributes per vertex'
complete -c pamtris -o tupletype -d 'This is the tuple type for the output PAM images'
complete -c pamtris -o rgb -d 'This is a convenience option which simply serves as an alias for -num_attribs…'
complete -c pamtris -o grayscale -d 'Another convenience option, similar to -rgb; except this one is an alias for …'
complete -c pamtris -o maxval -d 'Sets the maxval of the output PAM images, which is also the maximum permitted…'

