# pamtopng
# Autogenerated from man page /usr/share/man/man1/pamtopng.1.gz
complete -c pamtopng -o transparent -d 'pamtopng marks the specified color as transparent in the PNG image -- Every p…'
complete -c pamtopng -o background -d 'This causes pamtopng to create a background color chunk in the PNG output whi…'
complete -c pamtopng -o gamma -d 'This causes pamtopng to create a gAMA chunk'
complete -c pamtopng -o chroma -d 'This option specifies how red, green, and blue component values of a pixel sp…'
complete -c pamtopng -o srgbintent -d 'This asserts that the input is a pseudo-Netpbm image that uses an sRGB color …'
complete -c pamtopng -o text -d 'This option lets you include arbitrary text strings in the PNG output, as tEX…'
complete -c pamtopng -o ztxt -d 'The same as -text, except the text string is compressed in the PNG output'
complete -c pamtopng -o itxt -d 'Similar to -text, but the text strings can be in a language other than English'
complete -c pamtopng -o time -d 'This option allows you to specify the modification time value to be placed in…'
complete -c pamtopng -o interlace -d 'This causes the PNG file to be interlaced, in Adam7 format'
complete -c pamtopng -o verbose -d 'This causes the program to display various facts about the conversion. sp'
complete -c pamtopng -o palette -d o
complete -c pamtopng -o history -d o
complete -c pamtopng -o filter -d o
complete -c pamtopng -o size -d o
complete -c pamtopng -o paeth -d o
complete -c pamtopng -o hist -d o
complete -c pamtopng -o nofilter -d o
complete -c pamtopng -o sub -d o
complete -c pamtopng -o up -d o
complete -c pamtopng -o avg -d o
complete -c pamtopng -o force -d o
complete -c pamtopng -o libversion -d o
complete -c pamtopng -o compression -d o
complete -c pamtopng -o comp_xxx -d 'These are some of the other functions of pnmtopng that pamtopng lacks: o When…'
complete -c pamtopng -o rgb -d OPTIONS

