# pamtojpeg2k
# Autogenerated from man page /usr/share/man/man1/pamtojpeg2k.1.gz
complete -c pamtojpeg2k -o compression -d 'ratio is a floating point number that specifies the compression ratio'
complete -c pamtojpeg2k -o verbose -d 'This option causes pamtojpeg2k to issue informational messages about the conv…'
complete -c pamtojpeg2k -o debuglevel -d 'This option controls debug messages from the Jasper library'
complete -c pamtojpeg2k -o imgareatlx
complete -c pamtojpeg2k -o imgareatly
complete -c pamtojpeg2k -o tilegrdtlx
complete -c pamtojpeg2k -o tilegrdtly
complete -c pamtojpeg2k -o tilewidth
complete -c pamtojpeg2k -o tileheight
complete -c pamtojpeg2k -o prcwidth
complete -c pamtojpeg2k -o prcheight
complete -c pamtojpeg2k -o cblkwidth
complete -c pamtojpeg2k -o cblkheight
complete -c pamtojpeg2k -o mode
complete -c pamtojpeg2k -o ilyrrates
complete -c pamtojpeg2k -o numrlvls
complete -c pamtojpeg2k -o progression
complete -c pamtojpeg2k -o numgbits
complete -c pamtojpeg2k -o nomct
complete -c pamtojpeg2k -o sop
complete -c pamtojpeg2k -o eph
complete -c pamtojpeg2k -o lazy
complete -c pamtojpeg2k -o termall
complete -c pamtojpeg2k -o segsym
complete -c pamtojpeg2k -o vcausal
complete -c pamtojpeg2k -o pterm
complete -c pamtojpeg2k -o resetprob -d 'Other Options'

