# pamundice
# Autogenerated from man page /usr/share/man/man1/pamundice.1.gz
complete -c pamundice -o across -d 'This is the number of tiles across in the grid, i. e'
complete -c pamundice -o down -d 'This is the number of tiles up and down in the grid, i. e'
complete -c pamundice -o hoverlap -d 'This is the amount in pixels to overlap the tiles horizontally'
complete -c pamundice -o voverlap -d 'This is analogous to -hoverlap, but pamundice clips the bottom edge of each i…'
complete -c pamundice -o listfile -d 'This option names a file that contains the names of all the input files'
complete -c pamundice -o verbose -d 'Print information about the processing to Standard Error'

