# pamwipeout
# Autogenerated from man page /usr/share/man/man1/pamwipeout.1.gz
complete -c pamwipeout -o tb -o lr -d 'sp This option chooses between a vertical and a horizontal gradient'
complete -c pamwipeout -o ccw

