# pbmmake
# Autogenerated from man page /usr/share/man/man1/pbmmake.1.gz
complete -c pbmmake -o gray -d 'sp In addition to the usual -white and -black, this program implements -gray'
complete -c pbmmake -o white
complete -c pbmmake -o black

