# pbmnoise
# Autogenerated from man page /usr/share/man/man1/pbmnoise.1.gz
complete -c pbmnoise -o ratio -d 'The proportion of black pixels in the generated image'
complete -c pbmnoise -o pack -d 'The program generates pixels in 32-bit units discarding any fractional pixels…'
complete -c pbmnoise -o randomseed -d 'This is the seed for the random number generator that generates the pixels'
complete -c pbmnoise -o endian -d 'pbmnoise internally generates random 32-bit integers and uses the machine\'s b…'

