# pbmreduce
# Autogenerated from man page /usr/share/man/man1/pbmreduce.1.gz
complete -c pbmreduce -o threshold -d 'By default, pbmreduce does the halftoning after the reduction via boustrophed…'
complete -c pbmreduce -o floyd -o fs -d 'Specify the Floyd-Steinberg error diffusion method.   This is the default'
complete -c pbmreduce -o value -d 'sp This option alters the thresholding value for all quantizations'
complete -c pbmreduce -o randomseed -d 'This is the seed for the random number generator that controls the halftoning'

