# pbmtocis
# Autogenerated from man page /usr/share/man/man1/pbmtocis.1.gz
complete -c pbmtocis -s i -d 'Inverse: Reverse the mapping of foreground/background to black/white'
complete -c pbmtocis -s w -d 'If the input image is smaller than the fixed size of the output image, pad wi…'

