# pbmtextps
# Autogenerated from man page /usr/share/man/man1/pbmtextps.1.gz
complete -c pbmtextps -o font -d 'sp This specifies the font to use'
complete -c pbmtextps -o fontsize -d 'This is the size of the font in points'
complete -c pbmtextps -o resolution -d 'This is the resolution in dots per inch of distance measurements pertaining t…'
complete -c pbmtextps -o bottommargin -d 'These options control the margins added to the image, measured from the far e…'
complete -c pbmtextps -o descent -d 'These options control the margins added to the image, measured from the text …'
complete -c pbmtextps -o pad -d 'This pads the image on the top and bottom to the where the highest and lowest…'
complete -c pbmtextps -o crop -d 'This makes the program crop all sides to the far edge of the type'
complete -c pbmtextps -o stroke -d 'This is the width of line, in points, to use for stroke font'
complete -c pbmtextps -o verbose -d 'This option makes pbmtextps display extra information on Standard Error about…'
complete -c pbmtextps -o dump-ps -d 'This option makes pbmtextps write to Standard Output the Postscript program i…'
complete -c pbmtextps -o leftmargin -o rightmargin -o topmargin
complete -c pbmtextps -o ascent -d 'above the text baseline, and -descent adds white space to to the bottom to re…'

