# pbmtext
# Autogenerated from man page /usr/share/man/man1/pbmtext.1.gz
complete -c pbmtext -o wchar -d 'sp By default, pbmtext takes a single-byte character stream as input'
complete -c pbmtext -o builtin -d '-builtin selects a font among those built into Netpbm'
complete -c pbmtext -o space -d 'Add pixels pixels of space between characters'
complete -c pbmtext -o lspace -d 'Add pixels pixels of space between lines'
complete -c pbmtext -o nomargins -d 'By default, pbmtext adds margins all around the image as described above'
complete -c pbmtext -o width -d 'This specifies how much horizontal space the text is supposed to fit into'
complete -c pbmtext -o load-entire-font -d 'When you use a BDF font, pbmtext will normally load from the font     only th…'
complete -c pbmtext -o verbose -d 'This makes pbmtext issue informtional messages about its processing'
complete -c pbmtext -o dry-run -d 'sp With this option, instead of outputting an image of the text, pbmtext just…'
complete -c pbmtext -o text-dump -d 'This option causes pbmtext just to write to Standard Output the text in ASCII…'
complete -c pbmtext -o font
complete -c pbmtext -o invert

