# pbmtomacp
# Autogenerated from man page /usr/share/man/man1/pbmtomacp.1.gz
complete -c pbmtomacp -o norle -d 'This option tells pbmtomacp not to use any run length encoding compression in…'
complete -c pbmtomacp -o left -d '-right -top -bottom These options let you define a rectangle within the image…'
complete -c pbmtomacp -o right
complete -c pbmtomacp -o top
complete -c pbmtomacp -o bottom -d 'These options let you define a rectangle within the image to convert'

