# pbmtoescp2
# Autogenerated from man page /usr/share/man/man1/pbmtoescp2.1.gz
complete -c pbmtoescp2 -o compress -d 'This determines the compression mode that pbmtoescp2 uses in its output'
complete -c pbmtoescp2 -o resolution -d 'This determines the horizontal and the vertical print resolution set in the p…'
complete -c pbmtoescp2 -o stripeheight -d 'This option controls the height in lines of the stripes in the output'
complete -c pbmtoescp2 -o formfeed -d 'This option causes pbmtoescp2 to place a formfeed command at the end of the o…'
complete -c pbmtoescp2 -o raw -d 'This option causes pbmtoescp2 to generate only the data blocks'

