# pdbimgtopam
# Autogenerated from man page /usr/share/man/man1/pdbimgtopam.1.gz
complete -c pdbimgtopam -o verbose -d 'Display various interesting information about the input file and process'
complete -c pdbimgtopam -o notefile -d 'Write the image note (if any) to the specified file'

