# pgmtoppm
# Autogenerated from man page /usr/share/man/man1/pgmtoppm.1.gz
complete -c pgmtoppm -o black -d 'The program maps black pixels in the input to this color in the output'
complete -c pgmtoppm -o white -d 'The program maps white pixels in the input to this color in the output'
complete -c pgmtoppm -o map -d 'This option specifies a complete mapping of gray values in the input to     c…'

