# pngtopam
# Autogenerated from man page /usr/share/man/man1/pngtopam.1.gz
complete -c pngtopam -o verbose -d 'Display various information about the input PNG image and the conversion proc…'
complete -c pngtopam -o alphapam -d 'Produce a single output image containing the main image (foreground) and the …'
complete -c pngtopam -o alpha -d 'Output the transparency channel or transparency mask of the image'
complete -c pngtopam -o mix -d 'Compose the image with the transparency or transparency mask against a backgr…'
complete -c pngtopam -o background -d 'This option specifies the background color with which to mix the image when y…'
complete -c pngtopam -o gamma -d 'This option causes pngtopam to respect the image gamma information in the PNG…'
complete -c pngtopam -o text -d 'Writes the tEXt and zTXt chunks to a file, in a format as described in the pn…'
complete -c pngtopam -o time -d 'Prints the tIME chunk to stderr'
complete -c pngtopam -o byrow -d 'This option can make pngtopam run faster or in environments where it would ot…'
complete -c pngtopam -o orientraw -d 'A TIFF stream contains raster data which can be arranged in the stream variou…'

