# pnmcat
# Autogenerated from man page /usr/share/man/man1/pnmcat.1.gz
complete -c pnmcat -o topbottom -o tb -d 'Combine images vertically, top to bottom'
complete -c pnmcat -o leftright -o lr -d 'Combine images horizontally, left to right'
complete -c pnmcat -o jleft -o jcenter -o jright -d 'If the PNM images are not all the same height when you\'re concatenating left …'
complete -c pnmcat -o white -o black -d 'These options specify what color to use to fill in the extra space when doing…'
complete -c pnmcat -o jxxx -d 'PNMs on top of each other, flush with the left edge.   -leftright'
complete -c pnmcat -o jbottom -d 'aligned as if sitting on a table.  Margin Color'

