# pnmmercator
# Autogenerated from man page /usr/share/man/man1/pnmmercator.1.gz
complete -c pnmmercator -o inverse -d 'sp With this option a conversion from Mercator to degrees is applied'
complete -c pnmmercator -o nomix -d 'sp Default behaviour is that color blending is applied in between two adjacen…'
complete -c pnmmercator -o verbose -o vverbose -d 'sp This parameter outputs some additional information'
complete -c pnmmercator -o 90 -o 180 -d 'file will typically be twice as wide as high, but this is not a requirement'

