# pnmnorm
# Autogenerated from man page /usr/share/man/man1/pnmnorm.1.gz
complete -c pnmnorm -o wvalue -d 'sp To specify a percentage, use the -bpercent and -wpercent options, or you c…'
complete -c pnmnorm -o bsingle -d 'sp To specify that the single least brightness in the image should stretch to…'
complete -c pnmnorm -o maxexpand -d 'sp So that you can put a limit on the amount of expansion without having to e…'
complete -c pnmnorm -o keephues -d 'sp This option says to keep each pixel the same hue as it is in the input; ju…'
complete -c pnmnorm -o middle -d 'sp When you specify -midvalue=N, pnmnorm uses a quadratic function to map old…'
complete -c pnmnorm -o saturation -d 'sp -luminosity, -colorvalue, and -saturation determine what property of the p…'
complete -c pnmnorm -o bpercent
complete -c pnmnorm -o wpercent
complete -c pnmnorm -o bvalue
complete -c pnmnorm -o midvalue
complete -c pnmnorm -o luminosity -o colorvalue -d 'affect the transfer function (which is the same for all three RGB components)…'

