# pnmpsnr
# Autogenerated from man page /usr/share/man/man1/pnmpsnr.1.gz
complete -c pnmpsnr -o rgb -d 'This option causes pnmpsnr to compare the red, green, and blue components of …'
complete -c pnmpsnr -o machine -d 'This option causes pnmpsnr to report the PSNRs in machine-friendly form, so a…'
complete -c pnmpsnr -o max -d 'This is meaningful only with -machine'
complete -c pnmpsnr -o target -d 'This option causes pnmpsnr to run in comparison mode - rather than print the …'
complete -c pnmpsnr -o target3

