# pnmquant
# Autogenerated from man page /usr/share/man/man1/pnmquant.1.gz
complete -c pnmquant -o center
complete -c pnmquant -o meancolor
complete -c pnmquant -o meanpixel
complete -c pnmquant -o spreadbrightness
complete -c pnmquant -o spreadluminosity -d 'Options Passed to pnmremap'
complete -c pnmquant -o floyd
complete -c pnmquant -o fs
complete -c pnmquant -o nofloyd
complete -c pnmquant -o nofs
complete -c pnmquant -o norandom
complete -c pnmquant -o randomseed
complete -c pnmquant -o version

