# pnmscalefixed
# Autogenerated from man page /usr/share/man/man1/pnmscalefixed.1.gz
complete -c pnmscalefixed -o reduce -d 'sp These options determine the scale factors'
complete -c pnmscalefixed -o verbose -d 'sp Report details of the transformation'
complete -c pnmscalefixed -o xsize
complete -c pnmscalefixed -o width
complete -c pnmscalefixed -o ysize
complete -c pnmscalefixed -o height
complete -c pnmscalefixed -o xscale
complete -c pnmscalefixed -o yscale
complete -c pnmscalefixed -o pixels
complete -c pnmscalefixed -o xysize

