# pnmtoxwd
# Autogenerated from man page /usr/share/man/man1/pnmtoxwd.1.gz
complete -c pnmtoxwd -o directcolor -d 'sp Output in DirectColor format'
complete -c pnmtoxwd -o pseudodepth -d 'sp Set the depth of PseudoColor dump in bits'

