# pnmtorle
# Autogenerated from man page /usr/share/man/man1/pnmtorle.1.gz
complete -c pnmtorle -o verbose -d 'This option will cause pnmtorle to operate in verbose mode'
complete -c pnmtorle -o header -d 'This option causes the program to dump the header of the Netpbm image to be S…'
complete -c pnmtorle -o alpha -d 'This option causes pnmtorle to include a transparency channel in the output i…'
complete -c pnmtorle -o outfile -d 'If you specify this option, pnmtorle writes the output to this file'

