# pnmtopng
# Autogenerated from man page /usr/share/man/man1/pnmtopng.1.gz
complete -c pnmtopng -o verbose -d 'This causes pnmtopng to display information about the format of the output fi…'
complete -c pnmtopng -o downscale -d 'This enables pnmtopng to scale maxvalues of more then 65535 to 16 bits'
complete -c pnmtopng -o interlace -d 'This causes the PNG file to be interlaced, in Adam7 format'
complete -c pnmtopng -o alpha -d 'This specifies the transparency (alpha) channel of the image'
complete -c pnmtopng -o transparent -d 'pnmtopng marks the specified color as transparent in the PNG image'
complete -c pnmtopng -o background -d 'Causes pnmtopng to create a background color chunk in the PNG output which ca…'
complete -c pnmtopng -o palette -d 'This option specifies a palette to use in the PNG'
complete -c pnmtopng -o gamma -d 'Causes pnmtopng to create a gAMA chunk'
complete -c pnmtopng -o hist -d 'Use this parameter to create a chunk that specifies the frequency (or histogr…'
complete -c pnmtopng -o text -d 'This option lets you include arbitrary text strings in the PNG output, as tEX…'
complete -c pnmtopng -o ztxt -d 'The same as -text, except the text string is compressed in the PNG output'
complete -c pnmtopng -o rgb -d 'This option specifies how red, green, and blue component values of a pixel sp…'
complete -c pnmtopng -o size -d 'This option determines the aspect ratio of the individual pixels of your imag…'
complete -c pnmtopng -o srgbintent -d 'This asserts that the input is a pseudo-Netpbm image that uses an sRGB color …'
complete -c pnmtopng -o modtime -d 'This option allows you to specify the modification time value to be placed in…'
complete -c pnmtopng -o filter -d 'This option is obsolete.   Before Netpbm 10'
complete -c pnmtopng -o paeth -d 'Each of these options permits pnmtopng to use one type of row filter'
complete -c pnmtopng -o compression -d 'This option sets set the compression level of the zlib compression'
complete -c pnmtopng -o comp_mem_level -d 'This option sets the memory usage level of the zlib compression'
complete -c pnmtopng -o comp_strategy -d 'This options sets the compression strategy of the zlib compression'
complete -c pnmtopng -o comp_method -d 'This option does nothing'
complete -c pnmtopng -o comp_window_bits -d 'This option tells how big a window the zlib compression algorithm uses'
complete -c pnmtopng -o comp_buffer_size -d 'This option determines in what size pieces pnmtopng does the zlib compression'
complete -c pnmtopng -o force -d 'When you specify this, pnmtopng limits its optimizations'
complete -c pnmtopng -o libversion -d 'This option causes pnmtopng to display version information about itself and t…'
complete -c pnmtopng -o time
complete -c pnmtopng -o phys/-size -o phys -d 'multiple program arguments as the option argument, whereas -size takes a sing…'
complete -c pnmtopng -o nofilter
complete -c pnmtopng -o sub
complete -c pnmtopng -o up
complete -c pnmtopng -o avg

