# pnmtorast
# Autogenerated from man page /usr/share/man/man1/pnmtorast.1.gz
complete -c pnmtorast -o standard -d 'sp Forces the result to be in RT_STANDARD form'
complete -c pnmtorast -o rle -d 'sp Forces the result to be in RT_BYTE_ENCODED, which is smaller but, well, le…'

