# ppmpat
# Autogenerated from man page /usr/share/man/man1/ppmpat.1.gz
complete -c ppmpat -o gingham2 -o g2 -d 'A gingham check pattern.   Can be tiled'
complete -c ppmpat -o gingham3 -o g3 -d 'A slightly more complicated gingham.   Can be tiled'
complete -c ppmpat -o madras -d 'A madras plaid.   Can be tiled'
complete -c ppmpat -o tartan -d 'A tartan plaid.   Can be tiled'
complete -c ppmpat -o poles -d 'Color gradients centered on randomly-placed poles'
complete -c ppmpat -o squig -d 'Squiggley tubular pattern.   Can be tiled'
complete -c ppmpat -o camo -d 'Camouflage pattern. sp If you specify -color, give three or more colors'
complete -c ppmpat -o anticamo -d 'Anti-camouflage pattern - like -camo, but ultra-bright colors'
complete -c ppmpat -o argyle1 -d 'A diamond argyle pattern, without a cross through the diamond, with one diamo…'
complete -c ppmpat -o argyle2 -d 'A diamond argyle pattern, with a cross through the diamond, with one diamond'
complete -c ppmpat -o color -d 'This specifies the colors to appear in the pattern'
complete -c ppmpat -o mesh -d 'This option affects the patterns generated by the -gingham2, -gingham3, -madr…'
complete -c ppmpat -o randomseed -d 'This is the seed for the random number generator that generates the pixels'

