# ppmtopjxl
# Autogenerated from man page /usr/share/man/man1/ppmtopjxl.1.gz
complete -c ppmtopjxl -o nopack -d 'sp Generate a file which does not use the normal TIFF 4. 0 compression method'
complete -c ppmtopjxl -o gamma -d 'sp Set the gamma correction for the image'
complete -c ppmtopjxl -o dither -o cluster -o diffuse -d 'sp Alter the rendering algorithm used for images'
complete -c ppmtopjxl -o dark -d 'sp Enhance images with a dark background when they are reduced in size'
complete -c ppmtopjxl -o presentation -d 'sp Turn on presentation mode, in which two passes are made over the paper to …'
complete -c ppmtopjxl -o xsize -o ysize -d 'sp Resize the image'
complete -c ppmtopjxl -o width -o height -d 'sp Synonyms of -xsize and -ysize'
complete -c ppmtopjxl -o xscale -o yscale -d 'sp Alternatives to -xsize and -ysize.   Scale the image by a simple factor'
complete -c ppmtopjxl -o xshift -o yshift -d 'sp Shift the image on the page'

