# ppmtospu
# Autogenerated from man page /usr/share/man/man1/ppmtospu.1.gz
complete -c ppmtospu -o d0 -d 'The program does no dithering'
complete -c ppmtospu -o d2 -d 'The program uses a 2x2 ordered dither. sp This is the default'
complete -c ppmtospu -o d4 -d 'The program uses a 4x4 ordered dither'

