# ppmwheel
# Autogenerated from man page /usr/share/man/man1/ppmwheel.1.gz
complete -c ppmwheel -o huevalue -d 'This selects a hue-value color wheel. sp This option was new in Netpbm 10'
complete -c ppmwheel -o huesaturation -d 'This selects a hue-saturation color wheel'
complete -c ppmwheel -o maxval -d 'This selects the maxval for the image.   The default is 255'

