# procan
# Autogenerated from man page /usr/share/man/man1/procan.1.gz
complete -c procan -s '?' -d 'Print a help text to stdout describing command line options and available add…'
complete -c procan -o '??' -d 'Like -h, plus a list of the short names of all available address options'
complete -c procan -o '???' -d 'Like -hh, plus a list of all available address option names'
complete -c procan -s d -d 'Prints fatal, error, warning, and notice messages'

