# ristretto
# Autogenerated from man page /usr/share/man/man1/ristretto.1.gz
complete -c ristretto -s '?' -l help -d 'Show help options'
complete -c ristretto -l help-all -d 'Show all help options'
complete -c ristretto -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c ristretto -s v -l version -d 'Version information'
complete -c ristretto -l display -d 'X display to use'

