# systemd-pcrphase
# Autogenerated from man page /usr/share/man/man8/systemd-pcrphase.8.gz
complete -c systemd-pcrphase -l bank -d 'Takes the PCR banks to extend the specified word into'
complete -c systemd-pcrphase -l tpm2-device -d 'Controls which TPM2 device to use'
complete -c systemd-pcrphase -l graceful -d 'If no TPM2 firmware, kernel subsystem, kernel driver or device support is fou…'
complete -c systemd-pcrphase -s h -l help -d 'Print a short help text and exit'
complete -c systemd-pcrphase -l version -d 'Print a short version string and exit'
complete -c systemd-pcrphase -l phase -d 'switch).  OPTIONS'

