# thunar
# Autogenerated from man page /usr/share/man/man1/thunar.1.gz
complete -c thunar -l bulk-rename -d 'option is specified no file managers windows will be opened, but instead the …'
complete -c thunar -s '?' -l help
complete -c thunar -s V -l version
complete -c thunar -s B
complete -c thunar -l daemon
complete -c thunar -l display
complete -c thunar -s q -l quit

