# thunar-volman
# Autogenerated from man page /usr/share/man/man1/thunar-volman.1.gz
complete -c thunar-volman -s a -l device-added -d 'Manually tell thunar about a device'
complete -c thunar-volman -s c -l configure -d 'Configure management of removable drives and media'
complete -c thunar-volman -s v -l version -d 'Print version information and exit'
complete -c thunar-volman -l display -d 'X display to use AUTHOR Written by Benedikt Meurer <benny@xfce. org>'

