# thunar-volman-settings
# Autogenerated from man page /usr/share/man/man1/thunar-volman-settings.1.gz
complete -c thunar-volman-settings -s h -l help -d 'Show help options'
complete -c thunar-volman-settings -l help-all -d 'Show all help options'
complete -c thunar-volman-settings -l help-gtk -d 'Show GTK+ Options . PP GTK+ Options'
complete -c thunar-volman-settings -l class -d 'Program class as used by the window manager'
complete -c thunar-volman-settings -l name -d 'Program name as used by the window manager'
complete -c thunar-volman-settings -l screen -d 'X screen to use'
complete -c thunar-volman-settings -l sync -d 'Make X calls synchronous'
complete -c thunar-volman-settings -l gtk-module -d 'Load additional GTK+ modules'
complete -c thunar-volman-settings -l g-fatal-warnings -d 'Make all warnings fatal . SS "Application Options:"'
complete -c thunar-volman-settings -l display -d 'X display to use AUTHOR Written by Benedikt Meurer <benny@xfce. org>'

