# tred
# Autogenerated from man page /usr/share/man/man1/tred.1.gz
complete -c tred -s v -d 'Verbose output'
complete -c tred -s '?' -d 'Print usage information.  OPERANDS The following operand is supported:'

