# winicontopam
# Autogenerated from man page /usr/share/man/man1/winicontopam.1.gz
complete -c winicontopam -o allimages -d 'Convert all images in the input'
complete -c winicontopam -o image -d 'Convert image number index (starting with zero)'
complete -c winicontopam -o andmasks -d 'If the image to be extracted contains both graded transparency data and an AN…'
complete -c winicontopam -o verbose -d 'Print more messages'

