# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
complete -c x-window-manager -s h -l help -d 'Show help options'
complete -c x-window-manager -l help-all -d 'Show all help options'
complete -c x-window-manager -l help-gtk -d 'Show GTK+ Options'
complete -c x-window-manager -l help-sm-client -d 'Show session management options . SS "Application Options:"'
complete -c x-window-manager -l daemon -d 'Fork to the background'
complete -c x-window-manager -l compositor -d 'Set the compositor mode'
complete -c x-window-manager -l replace -d 'Replace the existing window manager'
complete -c x-window-manager -s V -l version -d 'Print version information and exit'
complete -c x-window-manager -l display -d 'X display to use Released under the terms of the GNU General Public License'

