# xfburn
# Autogenerated from man page /usr/share/man/man1/xfburn.1.gz
complete -c xfburn -s '?' -l help -d 'Show help options'
complete -c xfburn -l help-all -d 'Show all help options'
complete -c xfburn -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfburn -s i -l burn-image -d 'Open the burn image dialog'
complete -c xfburn -s b -l blank -d 'Open the blank disc dialog'
complete -c xfburn -s d -l data-composition -d 'Start a data composition'
complete -c xfburn -s V -l version -d 'Display program version and exit'
complete -c xfburn -s m -l main -d 'Show main program even when other action is specified on the command line'
complete -c xfburn -l display -d 'X display to use built with GTK+-2. 12. 11, linked with GTK+-2. 12. 11'

