# xfce4-kiosk-query
# Autogenerated from man page /usr/share/man/man8/xfce4-kiosk-query.8.gz
complete -c xfce4-kiosk-query -s h -d 'Show summary of options'
complete -c xfce4-kiosk-query -s v -d 'Show version of program'

