# xfce4-session-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-session-settings.1.gz
complete -c xfce4-session-settings -s '?' -l help -d 'Show help options'
complete -c xfce4-session-settings -l help-all -d 'Show all help options'
complete -c xfce4-session-settings -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfce4-session-settings -s s -l socket-id -d 'Settings manager socket'
complete -c xfce4-session-settings -s V -l version -d 'Version information'
complete -c xfce4-session-settings -l display -d 'X display to use COPYRIGHT Copyright © 2004-2008         The Xfce development…'

