# xfce4-settings-manager
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-manager.1.gz
complete -c xfce4-settings-manager -s h -l help -d 'Show help options'
complete -c xfce4-settings-manager -l help-all -d 'Show all help options'
complete -c xfce4-settings-manager -l help-gtk -d 'Show GTK+ Options . PP GTK+ Options'
complete -c xfce4-settings-manager -l class -d 'Program class as used by the window manager'
complete -c xfce4-settings-manager -l name -d 'Program name as used by the window manager'
complete -c xfce4-settings-manager -l screen -d 'X screen to use'
complete -c xfce4-settings-manager -l sync -d 'Make X calls synchronous'
complete -c xfce4-settings-manager -l gtk-module -d 'Load additional GTK+ modules'
complete -c xfce4-settings-manager -l g-fatal-warnings -d 'Make all warnings fatal . SS "Application Options:"'
complete -c xfce4-settings-manager -s V -l version -d 'Version information'
complete -c xfce4-settings-manager -s d -l dialog -d 'Settings dialog to show'
complete -c xfce4-settings-manager -l display -d 'X display to use COPYRIGHT Copyright © 2008-2011 The Xfce development team'

