# xfce4-about
# Autogenerated from man page /usr/share/man/man1/xfce4-about.1.gz
complete -c xfce4-about -s h -l help -d 'Show help options'
complete -c xfce4-about -l help-all -d 'Show all help options'
complete -c xfce4-about -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfce4-about -s V -l version -d 'Version information'
complete -c xfce4-about -l display -d 'X display to use COPYRIGHT Copyright © 2008-2011 The Xfce development team'

