# xfce4-appfinder
# Autogenerated from man page /usr/share/man/man1/xfce4-appfinder.1.gz
complete -c xfce4-appfinder -s h -l help -d 'Show help options'
complete -c xfce4-appfinder -l help-all -d 'Show all help options'
complete -c xfce4-appfinder -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfce4-appfinder -s c -l collapsed -d 'Start in collapsed mode'
complete -c xfce4-appfinder -s V -l version -d 'Print version information and exit'
complete -c xfce4-appfinder -s r -l replace -d 'Replace the existing service'
complete -c xfce4-appfinder -s q -l quit -d 'Quit all instances'
complete -c xfce4-appfinder -l disable-server -d 'Do not try to use or become a D-Bus service'
complete -c xfce4-appfinder -l display -d 'X display to use REPORTING BUGS Please report bugs to <http://bugzilla. xfce'

