# xfce4-settings-editor
# Autogenerated from man page /usr/share/man/man1/xfce4-settings-editor.1.gz
complete -c xfce4-settings-editor -s h -l help -d 'Show help options'
complete -c xfce4-settings-editor -l help-all -d 'Show all help options'
complete -c xfce4-settings-editor -l help-gtk -d 'Show GTK+ Options . PP GTK+ Options'
complete -c xfce4-settings-editor -l class -d 'Program class as used by the window manager'
complete -c xfce4-settings-editor -l name -d 'Program name as used by the window manager'
complete -c xfce4-settings-editor -l screen -d 'X screen to use'
complete -c xfce4-settings-editor -l sync -d 'Make X calls synchronous'
complete -c xfce4-settings-editor -l gtk-module -d 'Load additional GTK+ modules'
complete -c xfce4-settings-editor -l g-fatal-warnings -d 'Make all warnings fatal . SS "Application Options:"'
complete -c xfce4-settings-editor -s V -l version -d 'Version information'
complete -c xfce4-settings-editor -l display -d 'X display to use COPYRIGHT Copyright © 2008-2011 The Xfce development team'

