# xfce4-sensors
# Autogenerated from man page /usr/share/man/man1/xfce4-sensors.1.gz
complete -c xfce4-sensors -s h -l help -d 'Print this help dialog'
complete -c xfce4-sensors -s l -l license
complete -c xfce4-sensors -s v -l version

