# xfce4-accessibility-settings
# Autogenerated from man page /usr/share/man/man1/xfce4-accessibility-settings.1.gz
complete -c xfce4-accessibility-settings -s h -l help -d 'Show help options'
complete -c xfce4-accessibility-settings -l help-all -d 'Show all help options'
complete -c xfce4-accessibility-settings -l help-gtk -d 'Show GTK+ Options . PP GTK+ Options'
complete -c xfce4-accessibility-settings -l class -d 'Program class as used by the window manager'
complete -c xfce4-accessibility-settings -l name -d 'Program name as used by the window manager'
complete -c xfce4-accessibility-settings -l screen -d 'X screen to use'
complete -c xfce4-accessibility-settings -l sync -d 'Make X calls synchronous'
complete -c xfce4-accessibility-settings -l gtk-module -d 'Load additional GTK+ modules'
complete -c xfce4-accessibility-settings -l g-fatal-warnings -d 'Make all warnings fatal . SS "Application Options:"'
complete -c xfce4-accessibility-settings -s s -l socket-id -d 'Settings manager socket'
complete -c xfce4-accessibility-settings -s v -l version -d 'Version information'
complete -c xfce4-accessibility-settings -l display -d 'X display to use COPYRIGHT Copyright © 2008-2011 The Xfce development team'

