# xfconf-query
# Autogenerated from man page /usr/share/man/man1/xfconf-query.1.gz
complete -c xfconf-query -s h -l help -d 'Show help options . SS "Application Options:"'
complete -c xfconf-query -s V -l version -d 'Version information'
complete -c xfconf-query -s c -l channel -d 'The channel to query/modify'
complete -c xfconf-query -s p -l property -d 'The property to query/modify'
complete -c xfconf-query -s s -l set -d 'The new value to set for the property'
complete -c xfconf-query -s l -l list -d 'List properties (or channels if -c is not specified)'
complete -c xfconf-query -s v -l verbose -d 'Verbose output'
complete -c xfconf-query -s n -l create -d 'Create a new property if it does not already exist'
complete -c xfconf-query -s t -l type -d 'Specify the property value type'
complete -c xfconf-query -s r -l reset -d 'Reset property'
complete -c xfconf-query -s R -l recursive -d 'Recursive (use with -r)'
complete -c xfconf-query -s a -l force-array -d 'Force array even if only one element'
complete -c xfconf-query -s m -l monitor -d 'Monitor a channel for property changes'

