# xfrun4
# Autogenerated from man page /usr/share/man/man1/xfrun4.1.gz
complete -c xfrun4 -s h -l help -d 'Show help options'
complete -c xfrun4 -l help-all -d 'Show all help options'
complete -c xfrun4 -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfrun4 -s c -l collapsed -d 'Start in collapsed mode'
complete -c xfrun4 -s V -l version -d 'Print version information and exit'
complete -c xfrun4 -s r -l replace -d 'Replace the existing service'
complete -c xfrun4 -s q -l quit -d 'Quit all instances'
complete -c xfrun4 -l disable-server -d 'Do not try to use or become a D-Bus service'
complete -c xfrun4 -l display -d 'X display to use REPORTING BUGS Please report bugs to <http://bugzilla. xfce'

