# xfsettingsd
# Autogenerated from man page /usr/share/man/man1/xfsettingsd.1.gz
complete -c xfsettingsd -s h -l help -d 'Show help options'
complete -c xfsettingsd -l help-all -d 'Show all help options'
complete -c xfsettingsd -l help-gtk -d 'Show GTK+ Options'
complete -c xfsettingsd -l help-sm-client -d 'Show session management options . PP GTK+ Options'
complete -c xfsettingsd -l class -d 'Program class as used by the window manager'
complete -c xfsettingsd -l name -d 'Program name as used by the window manager'
complete -c xfsettingsd -l screen -d 'X screen to use'
complete -c xfsettingsd -l sync -d 'Make X calls synchronous'
complete -c xfsettingsd -l gtk-module -d 'Load additional GTK+ modules'
complete -c xfsettingsd -l g-fatal-warnings -d 'Make all warnings fatal . PP Session management options'
complete -c xfsettingsd -l sm-client-id -d 'Session management client ID'
complete -c xfsettingsd -l sm-client-disable -d 'Disable session management . SS "Application Options:"'
complete -c xfsettingsd -s V -l version -d 'Version information'
complete -c xfsettingsd -l no-daemon -d 'Do not fork to the background'
complete -c xfsettingsd -l replace -d 'Replace running xsettings daemon (if any)'
complete -c xfsettingsd -l display -d 'X display to use COPYRIGHT Copyright © 2008-2011 The Xfce development team'

