# xfwm4-settings
# Autogenerated from man page /usr/share/man/man1/xfwm4-settings.1.gz
complete -c xfwm4-settings -s h -l help -d 'Show help options'
complete -c xfwm4-settings -l help-all -d 'Show all help options'
complete -c xfwm4-settings -l help-gtk -d 'Show GTK+ Options . SS "Application Options:"'
complete -c xfwm4-settings -s s -l socket-id -d 'Settings manager socket'
complete -c xfwm4-settings -s V -l version -d 'Version information'
complete -c xfwm4-settings -l display -d 'X display to use'

