# xfwm4
# Autogenerated from man page /usr/share/man/man1/xfwm4.1.gz
complete -c xfwm4 -s h -l help -d 'Show help options'
complete -c xfwm4 -l help-all -d 'Show all help options'
complete -c xfwm4 -l help-gtk -d 'Show GTK+ Options'
complete -c xfwm4 -l help-sm-client -d 'Show session management options . SS "Application Options:"'
complete -c xfwm4 -l daemon -d 'Fork to the background'
complete -c xfwm4 -l compositor -d 'Set the compositor mode'
complete -c xfwm4 -l replace -d 'Replace the existing window manager'
complete -c xfwm4 -s V -l version -d 'Print version information and exit'
complete -c xfwm4 -l display -d 'X display to use Released under the terms of the GNU General Public License'

