# yuy2topam
# Autogenerated from man page /usr/share/man/man1/yuy2topam.1.gz
complete -c yuy2topam -o width -d 'Width of the image, in pixels.   This must be an even number'
complete -c yuy2topam -o height -d 'Height of the image. PP These options are mandatory'

